FROM node:16-alpine

WORKDIR '/usr/src/frontend'

COPY package.json ./
RUN npm install

COPY . .

# changing the ownership of the node_modules directory to the same 
# user running the npm command to avoid permission issues
RUN chown -R node:node /usr/src/frontend/node_modules

USER node

# Starts up a development server for dev use only
CMD [ "npm", "run", "start" ]
