sudo: required

services:
  - docker

before_install:
  - cp package.json frontend/
  - docker build -t ricardo072/docker-swarm-jenkins -f frontend/Dockerfile.dev .

script:
  - docker run -e CI=true ricardo072/docker-swarm-jenkins npm run test
